### ISSUE TITLE
Враг бездвижен

### ISSUE THREAD

**Issue by agarb7** [Typucm/Pacman#1]

**Comment by Typucm** [comment]
у меня он двигается

**Comment by Typucm** [comment]
Исправьте массив он в текстурке застрял у меня

**Comment by agarb7** [comment]
какой массив?

**Comment by Typucm** [comment]
массив карты

**Comment by agarb7** [comment]
у меня задвигался

**Comment by Typucm** [comment]
а ну все

**Comment by agarb7** [comment]
массив карты не трогал
враг в текстурах застрять не может, он же без обработки столкновений

**Comment by agarb7** [comment]
проверь у себя

**Comment by Typucm** [comment]
да все норм

**Comment by agarb7** [comment]
ты вытянул изменения из репы?

**Comment by Typucm** [comment]
нет

**Comment by Typucm** [comment]
как это?

**Comment by agarb7** [comment]
git pull

**Comment by Typucm** [comment]
я сделал, но код не изменился

**Comment by agarb7** [comment]
сделай git pull и приклей сюда скриншот

**Comment by Typucm** [comment]
![Uploading Безымянный.png . . .]()

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6688096/be82ff0c-cceb-11e4-8ace-4287dd71c46b.png)

**Comment by agarb7** [comment]
сделай опять
git pull
и потом
git status 
и пришли скрин

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6688299/4bb0c00c-cced-11e4-949d-1c6ad9c7afb0.png)

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6688379/d0df1c06-cced-11e4-97fd-11fe809b47b1.jpg)

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6688390/e15a681a-cced-11e4-831d-a0caf36f66b9.png)

**Comment by agarb7** [comment]
У тебя в каталоге репозитория изменения сделанные после коммита в ветку на сервере. А имеено какие-то новые файлы, если они тебе не нужны - удали их

**Comment by Typucm** [comment]
все я скачал, токо почему монстр теперь как эпилептик?)))

**Comment by Typucm** [comment]
как волчек

**Comment by agarb7** [comment]
у меня - нормально

**Comment by Typucm** [comment]
у меня очень быстро меняет направления

**Comment by agarb7** [comment]
это из-за какого-то различия в наших платформах

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6688532/2361edcc-ccef-11e4-8f2f-5186c1e13106.png)
может из за этого?

**Comment by agarb7** [comment]
нет

**Comment by Typucm** [comment]
все норм теперь я рандом немного подправил там было 100 я 10000 поставил он ходит нормально

**Comment by Typucm** [comment]
лучше чем было в той версии что вы мне скидывали в бгу
он не стоит а двигается постоянно

**Comment by agarb7** [comment]
но теперь у меня ходить перестанет

**Comment by Typucm** [comment]
дак я потом исправлю

**Comment by Typucm** [comment]
я не делал изменений на гите

**Comment by agarb7** [comment]
сейчас попробую сделать так чтобы у нас обоих работало

**Comment by agarb7** [comment]
ладно. тут по быстрому как я думал не поправишь. пока пусть остаётся так.

**Comment by Typucm** [comment]
конечно та один нулик в рандоме стереть или дописать не так уж и трудно

**Comment by agarb7** [comment]
но это не дело всё равно)

**Comment by Typucm** [comment]
лан давай пока разберемся со столкновениями

**Comment by Typucm** [comment]
я заметил вы закоментили коллижн? я так полагаю хотите заново написать столкновения что ли?

**Comment by agarb7** [comment]
да
