### ISSUE TITLE
Обработка столкновений со стенами

### ISSUE THREAD

**Issue by agarb7** [Typucm/Pacman#2]
сейчас не реализовано

**Comment by agarb7** [comment]
реализовал, но есть глюк.

**Comment by Typucm** [comment]
как? я кстати добавил еще одного монстра

**Comment by agarb7** [comment]
всё тут.
но монстра в репозитории не вижу)

**Comment by Typucm** [comment]
я его не заливал

**Comment by Typucm** [comment]
попробую залить я точком не умею

**Comment by Typucm** [comment]
я как понял он не может пройти вниз и вверх

**Comment by Typucm** [comment]
аа вижу...

**Comment by Typucm** [comment]
[i+1][j] почему вы прибавляете к этим значениям 1?

**Comment by agarb7** [comment]
проверяю попали ли какие-нибудь углы квадрата врага в квадрат блока

**Comment by Typucm** [comment]
аа я не могу залить суда изменения

**Comment by Typucm** [comment]
там я монстра добавил

**Comment by agarb7** [comment]
закоммить локально, а потом сделай гит пул. Он тебе либо автоматически смержит ветки, либо предложит тебе.
После того как смержишь, залей сюда

**Comment by Typucm** [comment]
у мменя одна и та же ошибка, там при git remote add origin https://github.com/Typucm/Pacman, already exists пишет мне

**Comment by Typucm** [comment]
типо существует

**Comment by agarb7** [comment]
git remote add origin - это ты добавляешь удалённый репозиторий. я же писал тебе.
это только раз нужно делать, когда новый удалённый реп появляется.

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6690679/ef95e8f0-ccfc-11e4-9c04-8ef7621f2152.png)

**Comment by Typucm** [comment]
что это а?

**Comment by agarb7** [comment]
это тру-хардкор редактор VIM.
сообщение к коммиту вверху напиши и сохрани.
погугли как пользоваться VIM или как сменить его на что-нибудь другое в git

**Comment by Typucm** [comment]
![default](https://cloud.githubusercontent.com/assets/11469956/6690920/41866012-ccfe-11e4-8a4c-a2c2554ea474.png)
вот такая ошибка

**Comment by agarb7** [comment]
git init
инициализирует репозиторий.
ты что хочешь сделать?

**Comment by Typucm** [comment]
я хочу добавить коммит

**Comment by agarb7** [comment]
git init - делается один раз когда создается реп
но сейчас проблема в другом.
у тебя других гитов не запущено?

**Comment by Typucm** [comment]
не знаю я пока разбирался кучу всего наделал так что скорее всего да

**Comment by agarb7** [comment]
закрой их все, или перезагрузи комп.
потом просто подготовь файлы (add) и закоммить (commit)
потом залей сюда (push).
т.е.
git add main.cpp
git commit -m 'Добавил ещё одного монстра'
git push

**Comment by Typucm** [comment]
сам сделай я по почте cpp отправлю, меня спать гонят

**Comment by agarb7** [comment]
ок

**Comment by agarb7** [comment]
монстра ты добавил неправильно.
